apiVersion: v1
kind: Service
metadata:
  name: {{ include "jpack-chart.fullname" . }}-jpack-svc
  labels:
    arterydocker/chart: {{ include "jpack-chart.name" . }}
    app.kubernetes.io/instance: "{{ include "jpack-chart.fullname" . }}-jpack-svc"
spec:
  selector:
    arterydocker/chart: {{ include "jpack-chart.name" . }}
    app.kubernetes.io/instance: "{{ include "jpack-chart.fullname" . }}-jpack-demo"
  type: NodePort
  ports:
    - name: tcp8080
      protocol: TCP
      port: 8080
      nodePort: {{ .Values.services.jpackSvc.nodeport.tcp8080 }}